version: '3.8'

services:
  lk-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.11.6
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        BUBBLE_TRANSCRIPT_ENDPOINT: ${BUBBLE_TRANSCRIPT_ENDPOINT}
        BUBBLE_GET_TRANSCRIPT_ENDPOINT: ${BUBBLE_GET_TRANSCRIPT_ENDPOINT}
        BUBBLE_STORY_ENDPOINT: ${BUBBLE_STORY_ENDPOINT}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BUBBLE_TRANSCRIPT_ENDPOINT=${BUBBLE_TRANSCRIPT_ENDPOINT}
      - BUBBLE_GET_TRANSCRIPT_ENDPOINT=${BUBBLE_GET_TRANSCRIPT_ENDPOINT}
      - BUBBLE_STORY_ENDPOINT=${BUBBLE_STORY_ENDPOINT}
    volumes:
      - .:/home/appuser
    ports:
      - "8000:8000"
    restart: always
